### PR TITLE
[WIP]Initial framework - ReactiveProperty generator

### LINKED ISSUE #1: [Feature] Roslyn Source Generators
I'm thinking about creating a source generator for the ReactiveUI project, similar to the [CommunityToolkit.Mvvm.SourceGenerators](https://github.com/CommunityToolkit/dotnet/issues/8).

My ideas are the following:

### ReactiveUI Property Source Generator

```csharp
[ReactiveProperty]
private DateTime _time;
```

Generates:

```csharp
public DateTime Time
{
    get => _time;
    set => this.RaiseAndSetIfChanged(ref _time, value);
}
```

### Observable As Property Helper Source Generator

```csharp
[OaphProperty]
private readonly ObservableAsPropertyHelper<string> _text;
```

Generates:

```csharp
public string Text => _text.Value;
```

I'm also considering that only the `[ReactiveProperty]` should be used and generate the appropriate property based on the type.

### DinamicData Property Source Generator

```csharp
[BindingProperty]
private readonly ReadOnlyObservableCollection<TrackViewModel> _tracks;
```

Generates:

```csharp
public ReadOnlyObservableCollection<TrackViewModel> InboundTracks => _tracks; 
```

---

Any idea?

### PR DESCRIPTION
**Pull request by adamradocz**
**What kind of change does this PR introduce?**

Closes #1

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

A very barebone framework to generate code. I created a PR to get feedback, is this the right direction?

### CODE REVIEW

**Comment by glennawatson** [comment]
Hey @adamradocz we had a bunch of notes on the requirements for this generator on Slack. Probably worth it for you to sign up there if you can. Tomáš Filip on there had started work as well.

One big problem I see it's not dual targeting roslyn 3.8 and roslyn 4, so we can't take advantage of multiple Visual Studio versions. Incremental generators are definitely great though.

Prefer no external dependencies if we can get away with it as well. Eg the CharGenerator stuff.

I will go through your PR and see how it matches up.

We had decided on some different naming for the attributes as well.

BTW I definitely appreciate the work you've done so far.

**Comment by adamradocz** [comment]
> Hey @adamradocz we had a bunch of notes on the requirements for this generator on Slack. Probably worth it for you to sign up there if you can. Tomáš Filip on there had started work as well.
> 
> One big problem I see it's not dual targeting roslyn 3.8 and roslyn 4, so we can't take advantage of multiple Visual Studio versions. Incremental generators are definitely great though.
> 
> Prefer no external dependencies if we can get away with it as well. Eg the CharGenerator stuff.
> 
> I will go through your PR and see how it matches up.
> 
> We had decided on some different naming for the attributes as well.
> 
> BTW I definitely appreciate the work you've done so far.

The `CharGenerator` has been left there unintentionally, it can be deleted.

Do you have any code? We can drop this one and continue with yours. Just wanted to get the ball rolling :)

**Comment by glennawatson** [comment]
We can go with your code, can you please add me as a collaborator to your project so I can bring the code in line with rxui standards?

**Comment by glennawatson** [comment]
btw again thanks for doing this :) I think you are further along than Tomáš anyway.

**Comment by adamradocz** [comment]
> btw again thanks for doing this :) I think you are further along than Tomáš anyway.

You're welcome. Where's the documentation? I can't find it on slack :)

**Pull request merged**
